name: CD-Liara
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i
          npm run start
          npm run generate
          npm i -g @liara/cli@2
          liara deploy --app="hekma-static" --path="dist" --api-token="$LIARA_TOKEN" --region iran --detach
